language: node_js
node_js: 10.13.0
cache:
  directories:
    - node_modules
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.51/hugo_0.51_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - hugo version
  - rm -rf public
  - npm install
script:
  - hugo --buildFuture
  - gulp
  - echo 'Build done!'
after_success:
  - cd public
  - scp -r ./ root@121.43.180.165:/home/www/blog;
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_1e28cf56e339_key -iv $encrypted_1e28cf56e339_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
addons:
  ssh_known_hosts: 121.43.180.165
notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=9d6aff336851fbc2e68992630091546a3e143c8de433e8a0f85cd1792c756456
